# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: cert update add-on
version: "1.2.1"
slug: cert
description: cert update add-on
url: "https://github.com/dolevhadad/addons-cert/tree/main/example"
arch:
  # - armhf
  # - armv7
  # - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
image: "ghcr.io/dolevhadad/amd64-addon-cert"
