name: "Cert Update"
description: "allow you to update cert on other servers!"
version: "1.2.3"
slug: "cert_update"
map:
  - ssl:rw
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
startup: services
options:
  CertLocation: []
  KeyLocation: []
  ServerUrl: []
  Port: []
schema:
  CertLocation:
    - str
  KeyLocation:
    - str
  ServerUrl:
    - str
  Port:
    - str