name: "Cert Update"
description: "My first real add-on!"
version: "1.2.0"
slug: "cert_update"
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
startup: services
ports:
  8000/tcp: 8000