name: "Cert Update"
description: "allow you to update cert on other servers!"
version: "1.2.3"
slug: "cert_update"
map:
  - ssl:rw
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
startup: services
options:
  CertLocation: fullchain.pem
  KeyLocation: privkey.pem
  Servers: {}
schema:
  CertLocation: str
  KeyLocation: str
  Servers:
    server1: str?
    port1: str?
    server2: str?
    port2: str?
    server3: str?
    port3: str?