name: "Cert Update"
description: "allow you to update cert on other servers!"
version: "1.2.3"
slug: "cert_update"
map:
  - ssl:rw
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
startup: services
options:
  CERT_LOCATION: fullchain.pem
  KEY_LOCATION: privkey.pem
  MIN_CERT_DATE: 75
  SERVERS: {}
schema:
  CERT_LOCATION: str
  KEY_LOCATION: str
  MIN_CERT_DATE: int
  SERVERS:
    SERVER1: str?
    PORT1: port?
    SERVER2: str?
    PORT2: port?
    SERVER3: str?
    PORT3: port?