name: "Cert Update"
description: "allow you to update cert on other servers!"
version: "1.2.3"
slug: "cert_update"
devicetree: true
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
startup: services
ports:
  8000/tcp: 8000